name: myenv
channels:
  - conda-forge
dependencies:
  # You need the pangeo-notebook conda-forge package in your environment.yml for compatibility with pangeo cloud deployments
  - pangeo-notebook==2022.07.12
  # The rest of the packages are up to you!
  - pip
  - pip:
    - git+https://github.com/scottyhq/jupyter-cloud-scoped-creds.git@main
